"""
ur8long_cell.launch.py

Thin launch wrapper generated by Motus Builder for robot 'ur8long_cell'.
Does NOT reimplement anything -- it includes robokpy_controller's own
cell.launch.py (NOT arm.launch.py directly: cell.launch.py is what
actually starts the Gazebo world, RViz, and the shared cell-level
services; including arm.launch.py alone starts the robot's own nodes
but no simulation ever runs, since nothing brings up a world for it --
confirmed the hard way against a real launch) and points it at THIS
package's URDF, meshes and config via the override args cell.launch.py
forwards straight through to arm.launch.py
(robot_description_path / robot_config_path / controllers_yaml_full_path /
mesh_package_name / external_xacro_args), plus objects_config_path (used
directly by cell.launch.py itself, for the shared object-catalog services
and the per-robot gripper.parent_link the object-catalog Gazebo plugin
needs). external_xacro_args is a JSON-encoded dict, baked in here at
generation time from whatever `motus robot add --arg name=value` this
robot was imported with (see robot_add.py's xacro_args) -- needed for any
source description whose OWN xacro:arg declarations have no safely-
reachable default (UR's name/ur_type/joint_limit_params/... being the
confirmed real-world case; a source with no such args just gets '{}'
here and this is a no-op). If robokpy_controller's launch internals
change later, this wrapper does not need to be regenerated.
"""

import os

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    use_sim_arg = DeclareLaunchArgument('use_sim', default_value='true')
    use_sim = LaunchConfiguration('use_sim')

    this_pkg_share = FindPackageShare('ur8long_cell_motus').find('ur8long_cell_motus')
    controller_pkg_share = FindPackageShare('robokpy_controller').find('robokpy_controller')

    cell_launch = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(controller_pkg_share, 'launch', 'cell.launch.py')),
        launch_arguments={
            'use_sim': use_sim,
            'robot_description_path': os.path.join(this_pkg_share, 'urdf', 'ur8long_cell.urdf.xacro'),
            'robot_config_path': os.path.join(this_pkg_share, 'config', 'robot.yaml'),
            'controllers_yaml_full_path': os.path.join(this_pkg_share, 'config', 'controllers.yaml'),
            'mesh_package_name': 'ur8long_cell_motus',
            'external_xacro_args': '{"name": "ur8long", "ur_type": "ur8long", "joint_limit_params": "/home/meta/Documents/robotics_workspace_new/Universal_Robots_ROS2_Description/config/ur8long/joint_limits.yaml", "kinematics_params": "/home/meta/Documents/robotics_workspace_new/Universal_Robots_ROS2_Description/config/ur8long/default_kinematics.yaml", "physical_params": "/home/meta/Documents/robotics_workspace_new/Universal_Robots_ROS2_Description/config/ur8long/physical_parameters.yaml", "visual_params": "/home/meta/Documents/robotics_workspace_new/ur8long_cell/src/ur8long_cell_motus/config/visual_parameters.yaml", "tf_prefix": "", "transmission_hw_interface": "", "safety_limits": "false", "safety_pos_margin": "0.15", "safety_k_position": "20", "force_abs_paths": "false"}',
            'objects_config_path': os.path.join(this_pkg_share, 'config', 'objects.yaml'),
        }.items(),
    )

    return LaunchDescription([
        use_sim_arg,
        cell_launch,
    ])
