"""
config_generator.py

Turns a KinematicAnalysis (kinematic_analyzer.py) into the two YAML files
a generated package needs: config/robot.yaml (same shape as
robokpy_controller's config/robots/<arm_type>.yaml) and
config/controllers.yaml (ros2_control controller_manager config).

IMPORTANT CONTRACT, discovered by reading arm.launch.py rather than
assumed: its controller spawners hardcode the controller NAMES
'joint_state_broadcaster', 'arm_controller', and 'gripper_action_controller'
as spawner arguments -- these are not configurable per-robot. Whatever
controllers.yaml this module writes MUST define controllers under those
exact names (or the spawners will fail to find them at launch), not
whatever names might seem natural for a given robot. This module has no
gripper information yet (kinematic_analyzer.py only walks the arm chain
and stops at the end-effector mount, by design), so it emits only
joint_state_broadcaster + arm_controller for now and leaves
gripper_action_controller out -- adding gripper joint control is a
follow-on step once the pipeline has a gripper/tool import path, not
something to guess at here.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .kinematic_analyzer import KinematicAnalysis

# Fallback limits used when a joint's URDF <limit> is missing a value.
# Conservative on purpose -- these should make a robot move cautiously
# rather than not at all, and every substitution is recorded as a
# warning so `motus doctor` can tell the user to fill in real values.
_DEFAULT_VELOCITY = 0.5   # rad/s
_DEFAULT_EFFORT = 50.0    # N*m


@dataclass
class ConfigGenerationResult:
    robot_yaml_text: str
    controllers_yaml_text: str
    warnings: list[str] = field(default_factory=list)


def _fmt_float(v: float) -> str:
    """%.6g strips the decimal point off whole numbers (0.0 -> '0'),
    which YAML then parses as an int, not a float -- and every
    rclpy-typed 'DOUBLE_ARRAY' parameter (home_pose, vel_limits, ...)
    rejects an int array outright at declare_parameter() time. Seen for
    real: home_pose is always all-zero, so this fired on every single
    generated robot.yaml, 100% of the time, not just as an edge case."""
    s = f"{v:.6g}"
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s


def _fmt_list(values: list[float]) -> str:
    return "[" + ", ".join(_fmt_float(v) for v in values) + "]"


def generate_configs(analysis: KinematicAnalysis, robot_name: str) -> ConfigGenerationResult:
    warnings: list[str] = []

    home_pose = [0.0] * analysis.dof
    vel_limits, acc_limits, pos_lo, pos_hi = [], [], [], []

    for j in analysis.chain_joints:
        lim = j.limit
        # Treat a present-but-zero velocity/effort the same as missing:
        # tested against a real vendor URDF (Elephant Robotics
        # mycobot_280_pi) that specifies velocity="0" on every joint --
        # schema-valid but physically meaningless (a robot that can't
        # move). `is None` alone would silently accept that.
        raw_vel = lim.velocity if lim else None
        if raw_vel is None or raw_vel <= 0:
            vel = _DEFAULT_VELOCITY
            reason = "missing" if raw_vel is None else f"present but {raw_vel} (not usable)"
            warnings.append(
                f"joint '{j.name}': velocity limit {reason} in the source description -- "
                f"using conservative default {_DEFAULT_VELOCITY} rad/s. Replace with the "
                f"real value in config/robot.yaml before relying on this for real hardware."
            )
        else:
            vel = raw_vel
        vel_limits.append(vel)

        # No acceleration/jerk data exists in URDF at all (URDF has no
        # such tag) -- these are always Motus-side estimates, not a
        # "missing from source" case, so no warning for this one.
        acc_limits.append(vel * 2.0)

        if lim is not None and lim.lower is not None and lim.upper is not None:
            pos_lo.append(lim.lower)
            pos_hi.append(lim.upper)
        elif j.type == "continuous":
            pos_lo.append(-3.14159265)
            pos_hi.append(3.14159265)
        else:
            pos_lo.append(-3.14159265)
            pos_hi.append(3.14159265)
            warnings.append(
                f"joint '{j.name}' ({j.type}): no position limits in the source "
                f"description -- using +/-pi as a placeholder. This joint's real "
                f"range MUST be set correctly before this robot is safe to move."
            )

    robot_yaml = f"""\
# Generated by Motus Builder from an imported robot description.
# Robot: {robot_name}
/**:
  ros__parameters:
    home_pose: {_fmt_list(home_pose)}
    marker_scale: 0.2
    publish_ee_path: True
    tool_type: none
    planning_base_link: {analysis.base_link}
    planning_tip_link: {analysis.tip_link}

motion_planner:
  ros__parameters:
    vel_limits: {_fmt_list(vel_limits)}
    acc_limits: {_fmt_list(acc_limits)}
    jerk_limits: {_fmt_list([a * 4.0 for a in acc_limits])}
    pos_limits_lo: {_fmt_list(pos_lo)}
    pos_limits_hi: {_fmt_list(pos_hi)}

kinematic_solver:
  ros__parameters:
    kinematic_solver_backend: pinocchio
"""

    joint_names_yaml = "\n".join(f"      - {name}" for name in analysis.joint_names)
    controllers_yaml = f"""\
# Generated by Motus Builder. Controller NAMES below (joint_state_broadcaster,
# arm_controller) are not arbitrary -- robokpy_controller's arm.launch.py
# spawns controllers by these exact names. Do not rename them here without
# also changing arm.launch.py's spawner arguments.
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
{joint_names_yaml}
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
"""

    return ConfigGenerationResult(
        robot_yaml_text=robot_yaml, controllers_yaml_text=controllers_yaml, warnings=warnings,
    )