"""
mycobot_pi.launch.py

Thin launch wrapper generated by Motus Builder for robot 'mycobot_pi'.
Does NOT reimplement anything -- it includes robokpy_controller's own
cell.launch.py (NOT arm.launch.py directly: cell.launch.py is what
actually starts the Gazebo world, RViz, and the shared cell-level
services; including arm.launch.py alone starts the robot's own nodes
but no simulation ever runs, since nothing brings up a world for it --
confirmed the hard way against a real launch) and points it at THIS
package's URDF, meshes and config via the override args cell.launch.py
forwards straight through to arm.launch.py
(robot_description_path / robot_config_path / controllers_yaml_full_path /
mesh_package_name). If robokpy_controller's launch internals change later,
this wrapper does not need to be regenerated.
"""

import os

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    use_sim_arg = DeclareLaunchArgument('use_sim', default_value='true')
    use_sim = LaunchConfiguration('use_sim')

    this_pkg_share = FindPackageShare('mycobot_pi_motus').find('mycobot_pi_motus')
    controller_pkg_share = FindPackageShare('robokpy_controller').find('robokpy_controller')

    cell_launch = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(controller_pkg_share, 'launch', 'cell.launch.py')),
        launch_arguments={
            'use_sim': use_sim,
            'robot_description_path': os.path.join(this_pkg_share, 'urdf', 'mycobot_pi.urdf.xacro'),
            'robot_config_path': os.path.join(this_pkg_share, 'config', 'robot.yaml'),
            'controllers_yaml_full_path': os.path.join(this_pkg_share, 'config', 'controllers.yaml'),
            'mesh_package_name': 'mycobot_pi_motus',
        }.items(),
    )

    return LaunchDescription([
        use_sim_arg,
        cell_launch,
    ])
