/**:
  ros__parameters:
    home_pose: [1.5697, -2.0535, 1.9318, -1.4490, -1.5708, 0.0]
    marker_scale: 0.2
    tool_type: robotiq_85
    planning_base_link: world
    planning_tip_link: tcp

motion_planner:
  ros__parameters:
    vel_limits: [3.0, 3.0, 4.0, 4.0, 5.0, 5.0]
    acc_limits: [10.0, 10.0, 15.0, 15.0, 20.0, 20.0]
    pos_limits_lo: [-6.28, -6.28, -3.14, -6.28, -6.28, -6.28]
    pos_limits_hi: [ 6.28,  6.28,  3.14,  6.28,  6.28,  6.28]

kinematic_solver:
  ros__parameters:
    kinematic_solver_backend: robokpy
