"""
ur5e_test.launch.py

Thin launch wrapper generated by Motus Builder for robot 'ur5e_test'.
Does NOT reimplement anything -- it includes robokpy_controller's own
arm.launch.py / cell.launch.py and points them at THIS package's URDF,
meshes and config via the override args those files accept
(robot_description_path / robot_config_path / controllers_yaml_full_path /
mesh_package_name). If robokpy_controller's launch internals change later,
this wrapper does not need to be regenerated.
"""

import os

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    use_sim_arg = DeclareLaunchArgument('use_sim', default_value='true')
    namespace_arg = DeclareLaunchArgument('namespace', default_value='arm1')
    use_sim = LaunchConfiguration('use_sim')
    namespace = LaunchConfiguration('namespace')

    this_pkg_share = FindPackageShare('ur5e_test_motus').find('ur5e_test_motus')
    controller_pkg_share = FindPackageShare('robokpy_controller').find('robokpy_controller')

    arm_launch = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(controller_pkg_share, 'launch', 'arm.launch.py')),
        launch_arguments={
            'namespace': namespace,
            'use_sim': use_sim,
            'robot_description_path': os.path.join(this_pkg_share, 'urdf', 'ur5e_test.urdf.xacro'),
            'robot_config_path': os.path.join(this_pkg_share, 'config', 'robot.yaml'),
            'controllers_yaml_full_path': os.path.join(this_pkg_share, 'config', 'controllers.yaml'),
            'mesh_package_name': 'ur5e_test_motus',
        }.items(),
    )

    return LaunchDescription([
        use_sim_arg, namespace_arg,
        arm_launch,
    ])
